### PR TITLE
Fix CUDA stack size indeterminacy

### LINKED ISSUE #170: CUDA stack size issue in `CouplingScheme::apply()`
These warnings are popping up when building on CUDA:
```
nvlink warning : Stack size for entry function '_ZN4RAJA6policy4cuda4impl18forall_cuda_kernelINS1_18cuda_exec_explicitINS_17iteration_mapping6DirectENS_4cuda11IndexGlobalILNS_9named_dimE0ELi256ELi0EEENS7_23MaxOccupancyConcretizerELm1ELb1EEELm1ENS_9Iterators16numeric_iteratorIiiPiEEZN6tribol14CouplingScheme5applyEidRdEUliE_iS6_SA_Lm256EEEvT2_T1_T3_' cannot be statically determined
```

Running the `tribol_common_plane_gpu` test then leads to stack overflow errors when run on release (output from `compute-sanitizer`):
```
========= Stack overflow
=========     at tribol::CheckInterfacePair(tribol::InterfacePair &, const tribol::MeshData::Viewer &, const tribol::MeshData::Viewer &, const tribol::Parameters &, tribol::ContactMethod, tribol::ContactCase, bool &, tribol::CompGeom::Viewer &, int *)+0x50
=========     by thread (0,0,0) in block (0,0,0)
=========         Device Frame: void RAJA::policy::cuda::impl::forall_cuda_kernel<RAJA::policy::cuda::cuda_exec_explicit<RAJA::iteration_mapping::Direct, RAJA::cuda::IndexGlobal<(RAJA::named_dim)0, (int)256, (int)0>, RAJA::cuda::MaxOccupancyConcretizer, (unsigned long)1, (bool)1>, (unsigned long)1, RAJA::Iterators::numeric_iterator<int, int, int *>, tribol::CouplingScheme::apply(int, double, double &)::[lambda(int) (instance 1)], int, RAJA::iteration_mapping::Direct, RAJA::cuda::IndexGlobal<(RAJA::named_dim)0, (int)256, (int)0>, (unsigned long)256>(T4, T3, T5)+0x2420
=========     Saved host backtrace up to driver entry point at kernel launch time
=========         Host Frame: cudaLaunchKernel [0x10d22c7] in tribol_common_plane_gpu_test
=========         Host Frame: std::enable_if<true, void>::type tribol::detail::forAllCudaImpl<__nv_hdl_wrapper_t<true, false, false, __nv_dl_tag<int (tribol::CouplingScheme::*)(int, double, double&), &tribol::CouplingScheme::apply, 1u>, void (int), axom::ArrayView<tribol::InterfacePair, 1, (axom::MemorySpace)0>, tribol::MeshData::Viewer, tribol::MeshData::Viewer, tribol::Parameters, tribol::ContactMethod, tribol::ContactCase, tribol::CompGeom::Viewer, axom::ArrayView<int, 1, (axom::MemorySpace)0>, axom::ArrayView<int, 1, (axom::MemorySpace)0> >, true, 256>(int, __nv_hdl_wrapper_t<true, false, false, __nv_dl_tag<int (tribol::CouplingScheme::*)(int, double, double&), &tribol::CouplingScheme::apply, 1u>, void (int), axom::ArrayView<tribol::InterfacePair, 1, (axom::MemorySpace)0>, tribol::MeshData::Viewer, tribol::MeshData::Viewer, tribol::Parameters, tribol::ContactMethod, tribol::ContactCase, tribol::CompGeom::Viewer, axom::ArrayView<int, 1, (axom::MemorySpace)0>, axom::ArrayView<int, 1, (axom::MemorySpace)0> >&&) [0x2c3541] in tribol_common_plane_gpu_test
=========         Host Frame: tribol::CouplingScheme::apply(int, double, double&) [0x2bbe4b] in tribol_common_plane_gpu_test
=========         Host Frame: tribol::update(int, double, double&) [0x2b0fa5] in tribol_common_plane_gpu_test
=========         Host Frame: double tribol::runExample<(tribol::MemorySpace)2, (tribol::ExecutionMode)1>(int) [0x2653fc] in tribol_common_plane_gpu_test
=========         Host Frame: tribol::CommonPlaneGPUTest::SetUp() [0x25e14d] in tribol_common_plane_gpu_test
=========         Host Frame: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) [0x3a5538] in tribol_common_plane_gpu_test
=========         Host Frame: testing::Test::Run() [0x388cf9] in tribol_common_plane_gpu_test
=========         Host Frame: testing::TestInfo::Run() [0x389def] in tribol_common_plane_gpu_test
=========         Host Frame: testing::TestSuite::Run() [0x38a954] in tribol_common_plane_gpu_test
=========         Host Frame: testing::internal::UnitTestImpl::RunAllTests() [0x39be6c] in tribol_common_plane_gpu_test
=========         Host Frame: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) [0x3a6228] in tribol_common_plane_gpu_test
=========         Host Frame: testing::UnitTest::Run() [0x39b9b9] in tribol_common_plane_gpu_test
=========         Host Frame: main [0x25b5ad] in tribol_common_plane_gpu_test
========= 
```

According to [this NVIDIA forum post](https://forums.developer.nvidia.com/t/a-meaning-of-nvlink-warning-stack-size-for-entry-function-cannot-be-statically-determined/27511), this means there is potentially some recursion in the kernel in `CouplingScheme::apply()` causing this.

### PR DESCRIPTION
**Pull request by ebchin**
Fixes #170

### CODE REVIEW

File: src/tribol/geom/CompGeom.cpp [hunk 1]
```diff
@@ -29,8 +29,14 @@ TRIBOL_HOST_DEVICE FaceGeomException CheckInterfacePairByMethod(
     InterfacePair& pair, const MeshData::Viewer& mesh1, const MeshData::Viewer& mesh2, const Parameters& params,
     ContactCase TRIBOL_UNUSED_PARAM( cCase ), bool& isInteracting, CompGeom::Viewer& cg, IndexT* plane_ct )
 {
-  T my_plane( &pair, params, mesh1.spatialDimension() );
-  FaceGeomException face_err = my_plane.checkInterfacePair( mesh1, mesh2 );
+  auto dim = mesh1.spatialDimension();
```
Comment (srwopschall) [inline src/tribol/geom/CompGeom.cpp:32]: This looks good. Was this just cleanup and simplification, i.e. getting rid of checkInterfacePair(), or was this required for the cuda stack issue?

File: src/tribol/geom/CompGeom.cpp [hunk 2]
```diff
@@ -227,7 +233,8 @@ TRIBOL_HOST_DEVICE FaceGeomException CommonPlanePair::checkFacePair( const MeshD
   m_face1_convex = IsConvex( x1_loc, y1_loc, mesh1.numberOfNodesPerElement() );
   m_face2_convex = IsConvex( x2_loc, y2_loc, mesh2.numberOfNodesPerElement() );
 
-  FaceGeomException interpen_err = this->computeOverlap3D(
+  // explicitly call compute overlap routine for common plane so CUDA can determine stack size
+  FaceGeomException interpen_err = CommonPlanePair::computeOverlap3D(
```
Comment (srwopschall) [inline src/tribol/geom/CompGeom.cpp:237]: Was this specifically the fix for the stack issue? Changing "this->" to "CommonPlanePair::" ?

I know mortar isn't ported, but for completeness and consistency should we make this change in the mortar and aligned mortar versions of checkFacePair etc.?

File: src/tribol/geom/CompGeom.hpp [hunk 3]
```diff
@@ -53,28 +53,6 @@ class ContactPlanePair : public CompGeomPair {
...
 
-  /*!
-   * \brief check to see if face-pairs are interacting
-   *
-   * \param [in] mesh1 mesh data viewer for mesh 1
-   * \param [in] mesh2 mesh data viewer for mesh 2
-   *
-   * \return face geometry exception
-   */
-  TRIBOL_HOST_DEVICE virtual FaceGeomException checkFacePair(
```
Comment (srwopschall) [inline src/tribol/geom/CompGeom.hpp:64]: It looks like these functions weren't changed, just moved location in the file? Please confirm.

**Review by srwopschall — APPROVED** [review]
Looks good. I had a few minor comments.
