### PR TITLE
Fix warnings, consistent include guards, clean up (some) includes

### LINKED ISSUE #152: C++ variable length arrays
When compiling LiDO codevelop which includes Tribol as a submodule, I get a few warnings about variable length arrays:
```
[353/1053] Building CXX object tribol/src/tribol/CMakeFiles/tribol.dir/integ/Integration.cpp.o
/home/user/current/lido/lido-2.0/smith/serac/tribol/src/tribol/integ/Integration.cpp:155:14: warning: variable length arrays in C++ are a Clang extension [-Wvla-cxx-extension]
  155 |   RealT bary[elem.dim * numTriPoints];
      |              ^~~~~~~~~~~~~~~~~~~~~~~
```

```
/home/user/current/lido/lido-2.0/smith/serac/tribol/src/tribol/integ/Integration.cpp:227:12: warning: variable length arrays in C++ are a Clang extension [-Wvla-cxx-extension]
  227 |   RealT xc[elem.dim];
```

### PR DESCRIPTION
**Pull request by ebchin**
This PR
 - Clears all warnings up to clang 19
 - Removes variable length C-style arrays
 - Changes include guard naming to be consistent
 - Removes some of the extraneous header includes in some of the test and source files.  Still some work to be done with this.

Follow-on PRs:
- Further cleanup of extraneous header file includes

### CODE REVIEW

File: src/tests/tribol_comp_geom_3d.cpp [hunk 1]
```diff
@@ -55,7 +55,7 @@ class CompGeomTest : public ::testing::Test {
   {
     // if element thickness is not registered by test, then register dummy
     // element thickness in order to use auto contact
-    RealT element_thickness[numCells];
+    tribol::Array1D<tribol::RealT> element_thickness( numCells );
```
Comment (srwopschall) [inline src/tests/tribol_comp_geom_3d.cpp:58]: Does this array wrap an axom array? I lost site of which "tribol arrays" we are keeping vs. using axom array.

File: src/tests/tribol_enzyme_nodal_normal.cpp [hunk 2]
```diff
@@ -67,7 +67,7 @@ class EnzymeNodalNormalTest : public testing::Test {
 
     mfem::DenseMatrix dndx_fd( num_dofs );
     auto mesh_view = mesh.getView();
-    Array2D<RealT> n_base = mesh_view.getNodalNormals();
+    axom::Array<RealT, 2> n_base = mesh_view.getNodalNormals();
```
Comment (srwopschall) [inline src/tests/tribol_enzyme_nodal_normal.cpp]: Clarify when to use an axom array explicitly vs a tribol array.

File: src/tests/tribol_iso_integ.cpp [hunk 3]
```diff
@@ -44,34 +41,21 @@ class IsoIntegTest : public ::testing::Test {
 
   bool integrate( RealT const tol )
   {
-    RealT xyz[this->dim * this->numNodes];
-    RealT* xy = xyz;
-
-    RealT* x = this->x;
-    RealT* y = this->y;
-    RealT* z = this->z;
+    // axom::primal::ZipIndexable<axom::primal::Vector<RealT, dim>> xyz;
```
Comment (srwopschall) [inline src/tests/tribol_iso_integ.cpp]: do you need to keep this primal line?

File: src/tests/tribol_iso_integ.cpp [hunk 4]
```diff
@@ -108,7 +92,6 @@ class IsoIntegTest : public ::testing::Test {
   void SetUp() override
   {
     this->numNodes = 4;
-    this->dim = 3;
```
Comment (srwopschall) [inline src/tests/tribol_iso_integ.cpp:111]: verify we don't actually need to set the dimension on the class.

File: src/tests/tribol_nodal_nrmls.cpp [hunk 5]
```diff
@@ -116,7 +111,7 @@ TEST_F( NodalNormalTest, two_quad_inverted_v )
   z[5] = -1.;
 
   // compute the nodal normals
-  computeNodalNormals( cellType, &x[0], &y[0], &z[0], &conn[0], numFaces, 6, 3 );
+  computeNodalNormals( cellType, x.data(), y.data(), z.data(), conn.data(), numFaces, 6 );
```
Comment (srwopschall) [inline src/tests/tribol_nodal_nrmls.cpp:114]: was dim simply not needed anymore in this routine?

File: src/tests/tribol_twb_integ.cpp [hunk 6]
```diff
@@ -40,34 +36,20 @@ class TWBIntegTest : public ::testing::Test {
...
+      xyz( j, 0 ) = x[j];
+      xyz( j, 1 ) = y[j];
+      xyz( j, 2 ) = z[j];
     }  // end loop over nodes
 
     // instantiate SurfaceContactElem struct. Note, this object is instantiated
     // using face 1 as face 2, but these faces are not used in this test so this
     // is ok.
-    tribol::SurfaceContactElem elem( this->dim, xy, xy, xy, this->numNodes, this->numNodes, nullptr, nullptr, 0, 0 );
+    tribol::SurfaceContactElem elem( this->dim, xyz.data(), xyz.data(), xyz.data(), this->numNodes, this->numNodes,
```
Comment (srwopschall) [inline src/tests/tribol_twb_integ.cpp:51]: I probably haven't gotten there yet, but xyz is laid out differently than xy was so I imagine a change propogated to the use of a SurfaceContactElem?

File: src/tests/tribol_twb_integ.cpp [hunk 7]
```diff
@@ -82,8 +64,8 @@ class TWBIntegTest : public ::testing::Test {
 
     for ( int a = 0; a < this->numNodes; ++a ) {
       for ( int ip = 0; ip < integ.numIPs; ++ip ) {
-        tribol::WachspressBasis( xy, integ.xy[dim * ip], integ.xy[dim * ip + 1], integ.xy[dim * ip + 2], this->numNodes,
-                                 a, phi );
+        tribol::WachspressBasis( xyz.data(), integ.xy[dim * ip], integ.xy[dim * ip + 1], integ.xy[dim * ip + 2],
```
Comment (srwopschall) [inline src/tests/tribol_twb_integ.cpp:67]: Same...I'm sure I'll see but did this function have to get refactored to accomodate the different coordinate layout?

File: src/tribol/common/Enzyme.hpp [hunk 8]
```diff
@@ -0,0 +1,55 @@
+// Copyright (c) 2017-2025, Lawrence Livermore National Security, LLC and
+// other Tribol Project Developers. See the top-level LICENSE file for details.
+//
+// SPDX-License-Identifier: (MIT)
+
+#ifndef SRC_TRIBOL_COMMON_ENZYME_HPP_
```
Comment (srwopschall) [inline src/tribol/common/Enzyme.hpp:6]: I'm skipping over this review assuming you've tested. Have you tested in Smith?

File: src/tribol/geom/Hyperplane.hpp [hunk 9]
```diff
@@ -0,0 +1,101 @@
...
+ *
+ * The `Hyperplane` type models a geometric hyperplane defined by an origin point and a normal vector. It provides
+ * basic operations such as projecting a point onto the hyperplane. The template parameter `_VectorT` allows using
+ * different vector storage/backing types.
+ *
+ * @tparam _T Element numeric type for vector components.
+ * @tparam _VectorT Vector type used for points and normals (defaults to `Vector<_T>`).
+ */
+template <typename _T, int _Dim, typename _VectorT = axom::primal::Vector<_T, _Dim>>
+class Hyperplane {
```
Comment (srwopschall) [inline src/tribol/geom/Hyperplane.hpp:32]: Let's discuss the intended use of this class and how it relates (if it does) to a contact plane.

File: src/tribol/physics/AlignedMortar.cpp [hunk 10]
```diff
@@ -170,8 +165,8 @@ void ComputeAlignedMortarGaps( CouplingScheme* cs )
   const IndexT numNodesPerFace = mortarMesh.numberOfNodesPerElement();
 
   // arrays to store face coords
-  RealT mortarX[dim * numNodesPerFace];
-  RealT nonmortarX[dim * numNodesPerFace];
+  Array2D<RealT> mortarX( numNodesPerFace, dim );
```
Comment (srwopschall) [inline src/tribol/physics/AlignedMortar.cpp:168]: Clarify reasoning between using Array2D<RealT> in places and ArrayT<RealT, dim> in others. Matter of preference?

File: src/tribol/physics/CommonPlane.cpp [hunk 11]
```diff
@@ -427,11 +427,9 @@ int ApplyTangential<COMMON_PLANE, PENALTY, VISCOUS_TANGENTIAL>( CouplingScheme*
   ///////////////////////////////
   // loop over interface pairs //
   ///////////////////////////////
-  ArrayT<int> err_data( { 0 }, cs->getAllocatorId() );
-  ArrayViewT<int> err = err_data;
   auto cs_view = cs->getView();
   const auto num_pairs = cs->getNumActivePairs();
-  forAllExec( cs->getExecutionMode(), num_pairs, [cs_view, err] TRIBOL_HOST_DEVICE( IndexT i ) {
```
Comment (srwopschall) [inline src/tribol/physics/CommonPlane.cpp:434]: clarify no longer returning an error.

**Review by srwopschall — CHANGES_REQUESTED** [review]
@ebchin - Looks good. Have some comments about minor clarifications etc.

File: src/tests/tribol_comp_geom_3d.cpp (hunk 1 above)
Comment (ebchin) [reply src/tests/tribol_comp_geom_3d.cpp:58]: Back to `axom::Array`

File: src/tests/tribol_iso_integ.cpp (hunk 3 above)
Comment (ebchin) [reply src/tests/tribol_iso_integ.cpp]: Nope, just did a test for the syntax at some point and forgot to remove.  Fixed

File: src/tests/tribol_enzyme_nodal_normal.cpp (hunk 2 above)
Comment (ebchin) [reply src/tests/tribol_enzyme_nodal_normal.cpp]: Good catch. Changed to `tribol::Array2D`. No need for explicit `axom::Array` anywhere now.

File: src/tests/tribol_iso_integ.cpp (hunk 4 above)
Comment (ebchin) [reply src/tests/tribol_iso_integ.cpp:111]: It's set in the `SetUp()` method, so it has to be 3 for all tests.  One could modify it in the test body, but this wouldn't build/pass CI, since it's a `constexpr` now.

File: src/tests/tribol_nodal_nrmls.cpp (hunk 5 above)
Comment (ebchin) [reply src/tests/tribol_nodal_nrmls.cpp:114]: Yeah, it wasn't used and causing a build warning.

File: src/tests/tribol_twb_integ.cpp (hunk 6 above)
Comment (ebchin) [reply src/tests/tribol_twb_integ.cpp:51]: No good catch, the data layout should not have changed.  Fixed.  Maybe a future PR with a derived `tribol::VectorArray` type might help standardize this.

File: src/tests/tribol_twb_integ.cpp (hunk 7 above)
Comment (ebchin) [reply src/tests/tribol_twb_integ.cpp:67]: Fixed

File: src/tribol/common/Enzyme.hpp (hunk 8 above)
Comment (ebchin) [reply src/tribol/common/Enzyme.hpp:6]: No testing in Smith yet.  Just addressing warnings in Tribol with this one.

File: src/tribol/geom/Hyperplane.hpp (hunk 9 above)
Comment (ebchin) [reply src/tribol/geom/Hyperplane.hpp:32]: I can remove this for now and bring it back when it's usage is clearer.

File: src/tribol/physics/AlignedMortar.cpp (hunk 10 above)
Comment (ebchin) [reply src/tribol/physics/AlignedMortar.cpp:168]: No difference. `Array2D<>` is my preference.  It seems clearer to me.

**Review by ebchin — COMMENTED** [review]
Thanks for the review @srwopschall , comments should be addressed now.

**Review by srwopschall — APPROVED** [review]
